version: "2"

services:

  banzai-caddy:
   container_name: "banzai-caddy"
   logging:
    driver: journald
    options:
     tag: "banzai-caddy"
   build: caddy
   volumes:
    - /volumes/$AWS_EFS_DNS_NAME/banzai/caddy:/root/.caddy
   ports:
    - "80:80"
    - "443:443"
   environment:
    - "CADDY_DOMAIN=${CADDY_DOMAIN}"
   entrypoint: "/usr/bin/caddy"
   command: ["--conf", "/etc/Caddyfile", "--log", "stdout", "--email", "${CADDY_EMAIL}"]
   depends_on:
    - banzai-jenkins
   restart: always

  banzai-jenkins:
   container_name: "banzai-jenkins"
   logging:
    driver: journald
    options:
     tag: "banzai-jenkins"
   build: jenkins
   volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /volumes/$AWS_EFS_DNS_NAME/banzai/jenkins_home:/var/jenkins_home
   ports:
    - "8080"
    - "50000:50000"
   restart: always
