version: "2"

services:

  banzai-nginx:
   container_name: "banzai-nginx"
   logging:
    driver: journald
    options:
     tag: "banzai-nginx"
   build: nginx
   ports:
    - "80:80"
   depends_on:
    - banzai-jenkins

  banzai-jenkins:
   container_name: "banzai-jenkins"
   logging:
    driver: journald
    options:
     tag: "banzai-jenkins"
   build: jenkins
   volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /volumes/$AWS_EFS_DNS_NAME/banzai/jenkins_home:/var/jenkins_home
   ports:
    - "8080"
    - "50000:50000"
