jenkinsmaster:
 build: jenkins-master
 volumes:
  - /usr/bin/docker:/usr/bin/docker
  - /var/run/docker.sock:/var/run/docker.sock
  - jenkins_log:/var/log/jenkins
  - jenkins_home:/var/jenkins_home
 ports:
  - "50000:50000"
jenkinsnginx:
 build: jenkins-nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkins-master
