version: "2"

volumes:
  jenkins_log:
    external: true
  jenkins_home:
    external: true

services:
  jenkins:
   build: jenkins
   volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins_log:/var/log/jenkins
    - jenkins_home:/var/jenkins_home
   ports:
    - "50000:50000"
  nginx:
   build: nginx
   ports:
    - "80:80"
   links:
    - jenkins
