version: "2"

volumes:
  jenkins_home:
    external: true
  jenkins_log:
    external: true

services:

  nginx:
   build: nginx
   ports:
    - "80:80"
   depends_on:
    - jenkins

  jenkins:
   build: jenkins
   volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins_home:/var/jenkins_home
    - jenkins_log:/var/log/jenkins
   ports:
    - "8080"
    - "50000:50000"
